// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvJFA4nUnufTjAnB5bDLqnlfj-8Cs1Mvg',
    appId: '1:784058023446:web:4499a1b8dc248c18cb7f37',
    messagingSenderId: '784058023446',
    projectId: 'book-a-ride-4772d',
    authDomain: 'book-a-ride-4772d.firebaseapp.com',
    storageBucket: 'book-a-ride-4772d.appspot.com',
    measurementId: 'G-1QSK9WCLB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA_YbsbP5klAHSvb420oeBxsr3TInVe1Y',
    appId: '1:784058023446:android:1086c8a12f5fb4cbcb7f37',
    messagingSenderId: '784058023446',
    projectId: 'book-a-ride-4772d',
    storageBucket: 'book-a-ride-4772d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIb1MZUycL924jMqqLhmnGDyZ6A8QKFlk',
    appId: '1:784058023446:ios:6275fe4b2fb191d3cb7f37',
    messagingSenderId: '784058023446',
    projectId: 'book-a-ride-4772d',
    storageBucket: 'book-a-ride-4772d.appspot.com',
    iosBundleId: 'com.example.bookARide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIb1MZUycL924jMqqLhmnGDyZ6A8QKFlk',
    appId: '1:784058023446:ios:6275fe4b2fb191d3cb7f37',
    messagingSenderId: '784058023446',
    projectId: 'book-a-ride-4772d',
    storageBucket: 'book-a-ride-4772d.appspot.com',
    iosBundleId: 'com.example.bookARide',
  );
}
